[package]
name = "tls"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1", default-features = false }
camino = { version = "1.1.7" }
dice-verifier.workspace = true
pem-rfc7468.workspace = true
rustls.workspace = true
x509-cert.workspace = true

