[workspace]
edition = "2021"
members = [
    "rot",
    "host",
    "common",
    "session",
]

default-members = [
    "rot",
    "host",
    "common",
    "session"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

