[workspace]
members = [
    "hyper-sprockets",
    "rot",
    "host",
    "common",
    "session",
]

default-members = [
    "hyper-sprockets",
    "rot",
    "host",
    "common",
    "session"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

