[workspace]
members = [
    "tls",
]

default-members = [
    "tls",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace.dependencies]
dice-verifier = { path = "../dice-util/verifier" }
serde = { version = "1", default-features = false }
thiserror = "1.0.57"
x509-cert = { version = "0.2.5" }
pem-rfc7468 = { version = "0.7.0"}
