[workspace]
members = [
    "tls",
    "hyper-sprockets",
    "rot",
    "host",
    "common",
    "session",
    "proxy", "tls",
]

default-members = [
    "tls",
    "hyper-sprockets",
    "rot",
    "host",
    "common",
    "session",
    "proxy",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace.dependencies]
salty.version = "0.3"
